#!/bin/bash


./DLSEDSpectrometer > /dev/null 2>&1 &
./DtAppSEDSpectrometer > /dev/null 2>&1 &
./ViewSEDSpectrometer > /dev/null 2>&1 &
./SALLV_sedSpectrometer_Monitor &

cd /home/harini/TCS/SEDSpectrum
python3 -m http.server --bind 140.252.32.244 8000
echo "started server"
